apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flask-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed-healthy.engineering-metrics-collector: ""
spec:
  description: Flask rest API demo project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'