apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: flask-project
  labels:
    app.kubernetes.io/component: flask-demo
    app.kubernetes.io/name: flask-demo
    app.kubernetes.io/part-of: flask-project
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-demo
    spec:
      initContainers:
      containers:
        - name: flask-demo
          env:
          image: docker.io/neerajtiwari/flask-app:549022bce371c39ebc759e740ef82f869382f404
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 12m
              memory: 64Mi
            limits:
              cpu: 12m
              memory: 64Mi
