apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: flask-project
  labels:
    application: flask-demo
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      application: flask-demo
  template:
    metadata:
      labels:
        application: flask-demo
    spec:
      initContainers:
      containers:
        - name: flask-demo
          env:
          image: docker.io/neerajtiwari/flask-app:549022bce371c39ebc759e740ef82f869382f404
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 20m
              memory: 128Mi
