apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: flask-demo
  labels:
    application: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      application: flask-demo
  template:
    metadata:
      labels:
        application: flask-demo
    spec:
      initContainers:
      containers:
        - name: flask-demo
          env:
          image: docker.io/neerajtiwari/flask-app:a76c4ad214ee1e009e31cad25317c92aa8228343
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 10m
              memory: 128Mi
