apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: flask-demo
  labels:
    application: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      application: flask-demo
  template:
    metadata:
      labels:
        application: flask-demo
    spec:
      initContainers:
      containers:
        - name: flask-demo
          env:
          image: docker.io/neerajtiwari/flask-app:8e6e8fb2556b0a73f28aae7cef60ed17b4188022
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 20m
              memory: 128Mi
