apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  namespace: flask-demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: flask-demo