apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  namespace: flask-project
  labels:
    app.kubernetes.io/component: flask-demo
    app.kubernetes.io/name: flask-demo
    app.kubernetes.io/part-of: flask-project
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app.kubernetes.io/name: flask-demo