apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  namespace: flask-project
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    application: flask-demo