name: Build & Push Docker image to docker hub

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          IMAGE: "neerajtiwari/flask-demo:$(var.GITHUB_RUN_ID)"
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: print tag
        run: echo "${{var.IMAGE}}"

      #- name: Build docker image
      #  run: docker build . -t ${{IMAGE}}

      #- name: Docker push
      #  run: docker push ${{IMAGE}}