name: Build & Push Docker image to docker hub

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          IMAGE=neerajtiwari/flask-demo:$GITHUB_RUN_ID:
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      #- name: print docker creds
      #  run: echo "${{secrets.DOCKER_USER}} & ${{secrets.DOCKER_PASSWORD}}"

      - name: Build docker image
        run: docker build --file Dockerfile -t ${{env.IMAGE}}

      - name: Docker push
        run: docker push ${{env.IMAGE}}